###
# This is the place to override the apache2 cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "apache2/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the Apache contact and timeout settings:
#
default[:apache][:version]             = '2.4'
default[:apache][:conf_available_dir]  = "#{node[:apache][:dir]}/conf-available"
default[:apache][:conf_enabled_dir]    = "#{node[:apache][:dir]}/conf-enabled"
