###
# This is the place to override the apache2 cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "apache2/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the Apache contact and timeout settings:
#

if node[:opsworks].has_key?("isVagrant")
	default[:apache][:user]          = 'vagrant'
	default[:apache][:group]         = 'vagrant'
else
	default[:apache][:user]          = 'deploy'
	default[:apache][:group]         = 'www-data'
end